version: '3.8'

services:
  exercise-api:
    image: exercise-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5454:80"
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge
