version: "3.8"

networks:
  kong-net:
    name: kong-net
    driver: bridge  

volumes:
  db_volume: 

services:
  exercise-api:
    build:
      context: .
      dockerfile: ExerciseDockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "AppSettings__DB_CONN=host=PF_db;port=5432;database=PersonalizeFit;username=postgres;password=2424"
    volumes:
      - ~/.aspnet/https:/https:ro    
    ports:
      - 8045:8045
    depends_on:
      - PF_db    
    restart: on-failure
    networks:
      - kong-net

  exercise-api-migrations:
    build:
      context: .
      dockerfile: ExerciseMigrationDockerfile
    depends_on:
      - PF_db
    restart: on-failure
    environment:
      - "AppSettings__DB_CONN=host=PF_db;port=5432;database=PersonalizeFit;username=postgres;password=2424"
    networks:
      - kong-net
    entrypoint: ./efbundle --connection "host=PF_db;port=5432;database=PersonalizeFit;username=postgres;password=2424"

  training-api:
    build:
      context: .
      dockerfile: TrainingDockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "AppSettings__DB_CONN=host=PF_db;port=5432;database=PersonalizeFit;username=postgres;password=2424"
    volumes:
      - ~/.aspnet/https:/https:ro    
    ports:
      - 8050:8050
    depends_on:
      - PF_db    
    restart: on-failure
    networks:
      - kong-net

  training-api-migrations:
    build:
      context: .
      dockerfile: TrainingMigrationDockerfile
    depends_on:
      - PF_db
    restart: on-failure
    environment:
      - "AppSettings__DB_CONN=host=PF_db;port=5432;database=PersonalizeFit;username=postgres;password=2424"
    networks:
      - kong-net
    entrypoint: ./efbundle --connection "host=PF_db;port=5432;database=PersonalizeFit;username=postgres;password=2424"

  user-api:
    build:
      context: .
      dockerfile: UserDockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "AppSettings__DB_CONN=host=PF_db;port=5432;database=PersonalizeFit;username=postgres;password=2424"
    volumes:
      - ~/.aspnet/https:/https:ro    
    ports:
      - 8040:8040
    depends_on:
      - PF_db    
    restart: on-failure
    networks:
      - kong-net

  user-api-migrations:
    build:
      context: .
      dockerfile: UserMigrationDockerfile
    depends_on:
      - PF_db
    restart: on-failure
    environment:
      - "AppSettings__DB_CONN=host=PF_db;port=5432;database=PersonalizeFit;username=postgres;password=2424"
    networks:
      - kong-net
    entrypoint: ./efbundle --connection "host=PF_db;port=5432;database=PersonalizeFit;username=postgres;password=2424"

  PF_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2424
      POSTGRES_DB: PersonalizeFit
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - "2346:5432"    
    networks:
      - kong-net